services:
  challenge-service:
    build:
      context: .
      dockerfile: Dockerfile

    image: challenge-service:local
    container_name: challenge-service

    ports:
      - "8080:8080"

    environment:
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"